tailscale-operator:
    oauth:
        clientId: ENC[AES256_GCM,data:LTVw6mrTzaEI1pbo7smegd8=,iv:Zgq4dv3WtEabTs9Rd/2+/rIwXZaaAIj0o3R1Gseih2U=,tag:ld1s3gWTQgzev4VmE1UZLw==,type:str]
        clientSecret: ENC[AES256_GCM,data:Nq7MhbgH3V0rhK3VQDTPb0ur0xeDn0blIXdSr1g3E+2f9zWdRTmPYPi2zb/MMP6REGqJgwNfFf21ES975Seezw==,iv:9PBB8wO+If8y9ZrL188CvFysoQ72tcB5j6KKLepL1FQ=,tag:PAdvsHZ1QEYe8Cb7Bau9ig==,type:str]
sops:
    age:
        - recipient: age1sxh3cuav8fa2vl6xzwld3xxa50zqyw9ckwf35f99mvn0xtlv9dusam7cfq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZU93Z001Rld3L3BNcUpl
            SjhlTXlacFBJQ3lYYmdzYjhycUtqZWVWNncwCnR5WEt4c1ZIRjl0ZnNNYXh6VXFV
            Q3NKQnhxcGYwUW5GOC9aeS9VL3JWSVEKLS0tIHU3M3plb1JZN0hvc1dOampncWdv
            YTNwOEpUbTNCN2ErQXZtcWtVMjhOOTQKB1OGY/GFfu1ppUmZNmCEo+6XI/btgKN+
            8kIXd3TaHG5d1X7tM6Ig0hA60NnK+Xzt4MuqEDO/se5zoBpCbsKF/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T13:27:14Z"
    mac: ENC[AES256_GCM,data:h3erTxj/kpU/WO9G02ZoGHJ66rudowgUUflPSI/1nw9yvgFqfUs98oUXohk7zkVSErvqwEd4/qc9wSPownLj8HLl1ZSNne5P+hFHSjfyo4au+qUR+Ww4WD1NcA4JWeLSW2urJB2p2AZ00CXdrPPYAYfV+JuErCphTQ5nLrqRTyI=,iv:lxVoh4KLqawlTjcDbcVc12MHKi1Uo4/AOXaPNiYPex4=,tag:weD+x42RKlhs3ulWUVwAkA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
